version: '3.8'

services:
  app:
    image: wflow-server:latest
    build: .
    ports:
      - "10000:10000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://cuslter-pm-2023.rwlb.zhangbei.rds.aliyuncs.com:3306/work_flow?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&tinyInt1isBit=false
      - SPRING_DATASOURCE_USERNAME=fanxin_pm_master
      - SPRING_DATASOURCE_PASSWORD=Fanxin@Sbz123!@#
    networks:
      - wflow-network

networks:
  wflow-network:
