#配置内置Tomcat端口
server:
  port: 10000
spring:
  application:
    name: wflow
  datasource:
  #配置数据源
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: flow
      #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        flow:
          url: jdbc:mysql://cuslter-pm-2023.rwlb.zhangbei.rds.aliyuncs.com:3306/work_flow?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&tinyInt1isBit=false
          username: fanxin_pm_master
          password: Fanxin@Sbz123!@#
          driverClassName: com.mysql.jdbc.Driver
        hr:
          url: jdbc:mysql://cuslter-pm-2023.rwlb.zhangbei.rds.aliyuncs.com:3306/hr?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&tinyInt1isBit=false
          username: fanxin_pm_master
          password: Fanxin@Sbz123!@#
          driverClassName: com.mysql.jdbc.Driver

  #  http:
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true
#  cloud:
#    nacos:
#      discovery:
#        # 配置所属命名空间的id，我们配置名称为dev的id，在命名空间列表查看id的值
#        namespace: sofa-rpc
#        # 配置所属分组
#        group: DEFAULT_GROUP
#        # nacos服务器地址
#        server-addr: bng.nacos.com
#  config:
#    activate:
#      on-profile:
#        - ${spring.profiles.active}
#    import:
#      - optional:nacos:application-${spring.profiles.active}.yml
#      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
  jackson:
    #字段为null时不返回该字段
    #default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      #单个文件大小
      max-file-size: 100MB
      #设置总共上传的文件大小
      max-request-size: 500MB

  #邮件发送配置
  mail:
    host: smtp.qq.com
    username: smartiots@qq.com
    password: fnrruelrccqaeaefx0
    protocol: smtps
    default-encoding: UTF-8
    properties:
      default-encoding: utf-8
      mail:
        smtp:
          port: 465
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: 192.168.70.106
      port: 6379
      password: 123456

management:
  health:
    mail: #忽略邮件健康检查
      enabled: false

#日志配置
logging:
  level:
    root: info
    # 打印日志
    com.wflow.mapper: debug

#mybatis配置
mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.wflow
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

flowable:
  #激活异步任务，审批超时事件需要
  async-executor-activate: true
  rest-api-enabled: false
  #关闭流程定义缓存，使用LRU，根据自己项目情况设置
  process:
    definition-cache-limit: 40960
  #关闭一些不需要的功能服务
  idm:
    enabled: false
  cmmn:
    enabled: false
  dmn:
    enabled: false
  app:
    enabled: false

wflow:
  file:
    max-size: 20 #最大文件上传大小，MB

sa-token:
  # token 名称 (同时也是cookie名称)
  token-name: wflowToken
  # token 有效期，单位s 默认30天, -1代表永不过期
  timeout: 172800
  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

web:
  domain: http://192.168.68.165:5173